# pub keys
keys:
  - &users:
    - &ta age1kzs3q70jcvug8h3u8uungpp89tjhnm7w5x4v0l6q3h4yh6n8ag8s0s5nqu #primate age key
    - &ta_grief age12dhkh4xr0qp0cl8vq93pc2yd5ayer3lf8yaatthuzce3vghjdq9qmgndrc
  - &hosts: # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &grief age1gn8y27xln2mpg4mx4fc43nspgdn44nlxfvjcrug4l2tckqtxtfqs3y3uml
    - &grief age1en5dul2tj70mtmkuduqufjt0zrmtxptvypudvlcv3ve3d2x2ea6q2uy5rz
creation_rules:
  #path should be relative to location of this file (.sops.yaml)
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *ta
        - *ta_grief
        - *grief
