# pub keys
keys:
  - &users:
    - &ta age1kzs3q70jcvug8h3u8uungpp89tjhnm7w5x4v0l6q3h4yh6n8ag8s0s5nqu #primate age key
    - &ta_grief age15xqn62qk4yrs2yd7ag4y2dcv2ty5q7vydn4zxauzeagyeaz47axqw02gl8
  - &hosts: # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &grief age1gn8y27xln2mpg4mx4fc43nspgdn44nlxfvjcrug4l2tckqtxtfqs3y3uml
    - &grief age13mt5lmtnpd6lvu4gwm7vsjn2rrpjnld5q3hvz2zw6nvaeu06pvfqnkxy3g
creation_rules:
  #path should be relative to location of this file (.sops.yaml)
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *ta
        - *ta_grief
        - *grief
